# Generated by Django 2.2.12 on 2021-12-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regastration',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
